name: Compile LaTeX
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Compile the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: template.tex
          latexmk_use_xelatex: true
      - name: Attach the PDF
        uses: actions/upload-artifact@v4
        with:
          name: document 
          path: template.pdf
          if-no-files-found: error
          retention-days: 7